[plugin]
repository = "https://github.com/HatTheTurtle/SAMMIWebhookPlugin.git"
commit = "be4c8cafd2f2bccb29254095027ee08c5461e093"
owners = ["HatTheTurtle"]
project_path = "SammiPlugin"
changelog = "Update for Dalamud API 11, added support for basic condition information"
